CREATE TABLE IF NOT EXISTS `contract_renewals` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `requested_by` VARCHAR(20),
  `requester_position` VARCHAR(100),
  `department` VARCHAR(100),
  `request_date` VARCHAR(20),
  `employee_id` VARCHAR(50),
  `employee_name` VARCHAR(100),
  `employee_department` VARCHAR(100),
  `position` VARCHAR(100),
  `current_start_date` VARCHAR(20),
  `current_end_date` VARCHAR(20),
  `current_duration` VARCHAR(50),
  `current_salary` VARCHAR(50),
  `proposed_start_date` VARCHAR(20),
  `proposed_end_date` VARCHAR(20),
  `proposed_duration` VARCHAR(50),
  `proposed_salary` VARCHAR(50),
  `reason_for_renewal` TEXT,
  `performance_summary` TEXT,
  `attendance_status` VARCHAR(50),
  `employee_remarks` TEXT,
  `discipline_status` VARCHAR(50),
  `renewal_recommendation` VARCHAR(50),
  `supervisor_recommendation` TEXT,
  `supporting_document` VARCHAR(255),
  `status` VARCHAR(20) DEFAULT 'Pending',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);