CREATE TABLE IF NOT EXISTS `hiring_approvals` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `requested_by` VARCHAR(20),
  `request_date` VARCHAR(20),
  `department` VARCHAR(100),
  `employee_name` VARCHAR(100),
  `employee_id` VARCHAR(50),
  `hiring_type` VARCHAR(50),
  `employee_replaced_id` VARCHAR(50),
  `number_of_vacancy` INT,
  `employment_type` VARCHAR(50),
  `work_location` VARCHAR(150),
  `required_start_date` VARCHAR(20),
  `reason_for_hiring` TEXT,
  `job_description` TEXT,
  `key_responsibilities` TEXT,
  `minimum_qualification` VARCHAR(255),
  `required_skills` TEXT,
  `required_experience` TEXT,
  `salary_range` VARCHAR(100),
  `budget_cost_center` VARCHAR(100),
  `hiring_priority` VARCHAR(20),
  `supporting_document` VARCHAR(255),
  `status` VARCHAR(20) DEFAULT 'Pending',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);
