CREATE TABLE IF NOT EXISTS `payroll_payment_requests` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `requested_by` VARCHAR(20),
  `requester_position` VARCHAR(100),
  `department` VARCHAR(100),
  `request_date` VARCHAR(20),
  `payment_type` VARCHAR(50),
  `payment_period` VARCHAR(20),
  `payee_name` VARCHAR(100),
  `employee_id` VARCHAR(50),
  `gross_amount` DECIMAL(10,2),
  `payment_description` TEXT,
  `bank_name` VARCHAR(100),
  `bank_account_number` VARCHAR(50),
  `requested_payment_date` VARCHAR(20),
  `cost_center` VARCHAR(100),
  `epf_amount` DECIMAL(10,2),
  `socso_amount` DECIMAL(10,2),
  `eis_amount` DECIMAL(10,2),
  `tax_amount` DECIMAL(10,2),
  `net_pay` DECIMAL(10,2),
  `remarks` TEXT,
  `supporting_document` VARCHAR(255),
  `status` VARCHAR(20) DEFAULT 'Pending',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);